version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:8080"
    environment:
      - RUN_MODE=production
      - APP_DATABASE_URL=postgresql://postgres:password@db:5432/reprime_backend
      - APP_SERVER_HOST=0.0.0.0
      - APP_SERVER_PORT=8080
      - APP_LOGGING_LEVEL=info
      - APP_LOGGING_FORMAT=json
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=reprime_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
