[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgresql://localhost/reprime_backend"
max_connections = 10
min_connections = 1
acquire_timeout = 30
idle_timeout = 600
max_lifetime = 1800

[logging]
level = "info"
format = "pretty"

[telemetry]
otlp_endpoint = "http://localhost:4317"
loki_endpoint = "http://localhost:3100"
service_name = "reprime-backend"
enable_tracing = true
enable_metrics = true
enable_logging = true
