[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgresql://localhost/reprime_backend"
max_connections = 10
min_connections = 1
acquire_timeout = 30
idle_timeout = 600
max_lifetime = 1800

[logging]
level = "info"
format = "pretty"

[telemetry]
otlp_endpoint = "http://localhost:4317"
loki_endpoint = "http://localhost:3100"
service_name = "reprime-backend"
enable_tracing = true
enable_metrics = true
enable_logging = true

[auth]
jwt_secret = "your-secret-key-change-in-production"
jwt_expiration_hours = 24

[auth.openfga]
endpoint = "http://localhost:8080"
store_id = "01JYTQW0GAD7KK4WDVWSCZ1ECJ"
auth_model_id = "01JYTQW0J85WGR952C2M09JZAC"
api_token = ""
cache_enabled = true
cache_ttl_seconds = 300
cache_max_entries = 50000
request_timeout_seconds = 30
