[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgresql://localhost/reprime_backend_dev"
max_connections = 5
min_connections = 1
acquire_timeout = 30
idle_timeout = 600
max_lifetime = 1800

[logging]
level = "debug"
format = "json"

[telemetry]
otlp_endpoint = "http://localhost:4317"
loki_endpoint = "http://localhost:3100"
service_name = "reprime-backend-dev"
enable_tracing = true
enable_metrics = true
enable_logging = true
