[server]
host = "0.0.0.0"
port = 8080

[database]
url = "postgresql://localhost/reprime_backend_prod"
max_connections = 20
min_connections = 5
acquire_timeout = 30
idle_timeout = 600
max_lifetime = 1800

[logging]
level = "info"
format = "json"

[telemetry]
otlp_endpoint = "http://tempo:4317"
loki_endpoint = "http://loki:3100"
service_name = "reprime-backend"
enable_tracing = true
enable_metrics = true
enable_logging = true
